server:
  port: 8085
spring:
  application:
    name: orderClient
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: jhmq
#    password: jhsjmy@QN
#    url: jdbc:mysql://rm-2ze31k797234tcx2v.mysql.rds.aliyuncs.com:3306/wxorder?characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
    url: jdbc:mysql://10.130.24.111:3306/wxorder?characterEncoding=utf-8&useSSL=false


feign:
  httpclient:
    enabled: true
